### ISSUE TITLE
Minecraft Crashes When Changing Category

### ISSUE THREAD

**Issue by zesskyo** [RedLime/SpeedRunIGT#132] opened 2024-03-29 19:20 UTC
**Describe the bug**
Self explanatory. Every time I go to change the category from Any% to an other category, it immediately crashes.

**To Reproduce**
1. Go to SpeedrunIGT settings
2. Click on Timer Category
3. Change the category to anything
4. Crash

**Expected behavior**
Should be able to change the category

**Versions info :**
 - MC Version: 1.20.4
 - SpeedRunIGT Version: 13.6
 - Fabric Loader Version: 0.15.7

**Additional context**
Trying to change it to Custom so I can play BAC :)

**Comment by tildejustin** [comment] 2024-03-29 20:42
duplicate of #106, fixed in an upcoming update. if you want to use it for B&C and don't care about verifiability, there is a pre-release of 14.1 [here](https://github.com/RedLime/SpeedRunIGT/releases/tag/14.1).

**Closed as completed** 2024-05-09 15:15 UTC
Labels: bug
